name: Changelog CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
        
  push:
    branches: 
      - 'main'

jobs:
  create-changelog:
    permissions:
      contents: 'write'  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set current date as env variable
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y.%m.%d%H%M%S')"
          
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ steps.date.outputs.date }}
          committer_username: ${{ github.actor }}
          config_file: .github/workflows/changeLogConfig.json
          changelog_filename: .github/workflows/latestLogs.md
        id: changelog-ci
      - run: |
          echo "${{ steps.changelog-ci.outputs.changelog }}"
