name: Release Notes CI

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        id: changelog-ci
      - run: |
          echo "${{ steps.changelog-ci.outputs.changelog }}"
