name: Release Notes CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
        
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ github.event.inputs.release_version }}
        id: changelog-ci
      - run: |
          echo "${{ steps.changelog-ci.outputs.changelog }}"
