name: Release Notes CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      release_version:
        description: 'Set Release Version'
        required: true
      tags:
        description: 'Test scenario tags'  
        
  push:
    branches: 
      - 'main'

jobs:
  approved:
    permissions:
      contents: 'write'  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: $(date +'%Y.%m.%dT%H%M%S')
          committer_username: ${{ github.actor }}
          config_file: .github/workflows/changeLogConfig.json
        id: changelog-ci
      - run: |
          echo "${{ steps.changelog-ci.outputs.changelog }}"
