
name: Create Release CI
on:
  workflow_dispatch:
    inputs:
        release_version:
          description: 'Set Release Version'
          required: true
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-changelog:
    permissions:
      contents: 'write'  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cleanup previous output
        run: |
          rm -rf .github/changelogs/latest.md
      - name: Set current date as env variable
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y.%m.%d%H%M%S')"
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ steps.date.outputs.date }}
          committer_username: ${{ github.actor }}
          config_file: .github/changelogs/config.json
          changelog_filename: .github/changelogs/latest.md
        id: changelog-ci
      - run: |
          echo "${{ steps.changelog-ci.outputs.changelog }}"
          
  create-release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes

  update-blog:
    name: Update lazarusengine.xyz
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Read changelogs
        id: readLog
        run: |
          content=$(jq -Rs . < .github/changelogs/latest.md)
          echo "::set-output name=data::${content}"
      - name: Update website release notes
        shell: bash
        run: |
          curl --request POST --url "https://lazarus-server.onrender.com/addChangeLog" --header "Content-Type: application/json" --data '{"date": "$(date +'%Y.%m.%d%H%M%S')", "title": "${{ github.ref_name#v }}", "description": "CI release notes", "changeLog":${{ steps.readLog.outputs.data }}}' --include
