
name: Create Release CI
on:
  workflow_dispatch:
    inputs:
        release_version:
          description: 'Set Release Version'
          required: true
  push:
    tags:
      - "v*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tag: ${{ github.ref_name }}
  
jobs:     
  create-release:
    permissions:
      contents: 'write'  
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag#v" \
              --generate-notes

  update-blog:
    name: Update lazarusengine.xyz
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Read changelogs
        id: readLog
        run: |
          content=$(jq -Rs . < .github/changelogs/latest.md)
          echo "::set-output name=data::${content}"
      - name: Update website release notes
        shell: bash
        run: |
          curl --request POST --url "https://lazarus-server.onrender.com/addChangeLog" --header "Content-Type: application/json" --data '{"date": "$(date +'%Y.%m.%d%H%M%S')", "title": "${{ env.tag }}", "description": "CI release notes", "changeLog":${{ steps.readLog.outputs.data }}}' --include
